# Generated by Django 4.2.21 on 2025-06-14 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('EXECUTED', 'EXECUTED'), ('PARTIALLY_EXECUTED', 'PARTIALLY_EXECUTED'), ('CANCELLED', 'CANCELLED')], max_length=32)),
                ('filled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('original_qty', models.PositiveIntegerField()),
                ('filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('EXECUTED', 'EXECUTED'), ('PARTIALLY_EXECUTED', 'PARTIALLY_EXECUTED'), ('CANCELLED', 'CANCELLED')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
