# Generated by Django 4.2.21 on 2025-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitorder',
            name='qty',
        ),
        migrations.AlterField(
            model_name='limitorder',
            name='direction',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='limitorder',
            name='original_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='limitorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('EXECUTED', 'EXECUTED'), ('PARTIALLY_EXECUTED', 'PARTIALLY_EXECUTED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
    ]
