# Generated by Django 4.2.21 on 2025-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_limitorder_qty_alter_limitorder_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('EXECUTED', 'EXECUTED'), ('PARTIALLY_EXECUTED', 'PARTIALLY_EXECUTED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=20),
        ),
    ]
