# Generated by Django 4.2.21 on 2025-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
    ]
